name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: Push release to CocoaPods Trunk

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Cocoapods
        run: |
         pod lib lint --allow-warnings
         pod trunk push --allow-warnings
        shell: bash
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
